name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Corrigir permissões do binário Cypress
        run: chmod +x node_modules/.bin/cypress

      - name: Install Cypress binary
        run: npx cypress install

      - name: Debug Cypress binário
        run: ls -l node_modules/.bin/cypress
        
      - name: Run Cypress tests
        run: npx cypress run
