name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Cypress binary
        run: npx cypress install

      - name: Run Cypress tests
        run: |
          export TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }}
          export TRELLO_API_TOKEN=${{ secrets.TRELLO_API_TOKEN }}
          npx cypress run
